DNN_kwargs = {
              'hidden_layer_sizes'    : (100,),
              'activation'            : 'relu',
              'solver'                : 'lbfgs',
              'alpha'                 : 1E-4,
              'batch_size'            : 'auto',
              'learning_rate'         : 'constant',
              'learning_rate_init'    : 1E-3,
              'power_t'               : 5E-1,
              'max_iter'              : 200,
              'shuffle'               : True,
              'random_state'          : None,
              'tol'                   : 1E-4,
              'verbose'               : False,
              'warm_start'            : False,
              'momentum'              : 9E-1,
              'nesterovs_momentum'    : True,
              'early_stopping'        : False,
              'validation_fraction'   : 1E-1,
              'beta_1'                : 9E-1,
              'beta_2'                : 999E-3,
              'epsilon'               : 1E-8,
              'n_iter_no_change'      : 10,
              'max_fun'               : 15E3,
             }

ANSI_keys = [
             '\x1b[24;2~',
             '\x1b[23;2~',
             '\x1b[21;2~',
             '\x1b[20;2~',
             '\x1b[19;2~',
             '\x1b[18;2~',
             '\x1b[17;2~',
             '\x1b[15;2~',
             '\x1b[1;2P',
             '\x1b[1;2Q',
             '\x1b[1;2S',
             '\x1b[200~',
             '\x1b[29~',
             '\x1b[31~',
             '\x1b[23~',
             '\x1b[33~',
             '\x1b[34~',
             '\x1b[21~',
             '\x1b[28~',
             '\x1b[26~',
             '\x1b[24~',
             '\x1b[25~',
             '\x1b[32~',
             '\x1b[20~',
             '\x1b[11~',
             '\x1b[17~',
             '\x1b[18~',
             '\x1b[63~',
             '\x1b[19~',
             '\x1b[62~',
             '\x1b[15~',
             '\x1b[14~',
             '\x1b[13~',
             '\x1b[12~',
             '\x1b[3~',
             '\x1b[[E',
             '\x1b[4~',
             '\x1b[[D',
             '\x1b[[C',
             '\x1b[[A',
             '\x1b[8~',
             '\x1b[2~',
             '\x1b[7~',
             '\x1b[6~',
             '\x1b[5~',
             '\x1b[[B',
             '\x1b[1~',
             '\x1b[E',
             '\x1bOR',
             '\x1bOH',
             '\x1b[Z',
             '\x1bOP',
             '\x1bOQ',
             '\x1bOS',
             '\x1b[G',
             '\x1bOF',
             '\x1bOD',
             '\x1bOC',
             '\x1bOB',
             '\x1bOA',
             '\x1b[F',
             '\x1b[H',
             '\x1b[D',
             '\x1b[B',
             '\x1b[A',
             '\x1b[C',
             '\r',
             '\x7f',
             '\t',
             ' ',
             'a',
             'b',
             'c',
             'd',
             'e',
             'f',
             'g',
             'h',
             'i',
             'j',
             'k',
             'l',
             'm',
             'n',
             'o',
             'p',
             'q',
             'r',
             's',
             't',
             'u',
             'v',
             'w',
             'x',
             'y',
             'z',
             'æ',
             'ø',
             'å',
             '0',
             '1',
             '2',
             '3',
             '4',
             '5',
             '6',
             '7',
             '8',
             '9'
            ]

ANSI_values = [
               'F24',
               'F23',
               'F22',
               'F21',
               'F20',
               'F19',
               'F18',
               'F17',
               'F13',
               'F14',
               'F16',
               'BracketedPaste',
               'F16',
               'F17',
               'F11',
               'F19',
               'F20',
               'F10',
               'F15',
               'F14',
               'F12',
               'F13',
               'F18',
               'F9',
               'F1',
               'F6',
               'F7',
               'ScrollDown',
               'F8',
               'ScrollUp',
               'F5',
               'F4',
               'F3',
               'F2',
               'Delete',
               'F5',
               'End',
               'F4',
               'F3',
               'F1',
               'End',
               'Insert',
               'Home',
               'PgDn',
               'PgUp',
               'F2',
               'Home',
               'Ignore',
               'F3',
               'Home',
               'BackTab',
               'F1',
               'F2',
               'F4',
               'Ignore',
               'End',
               'Left',
               'Right',
               'Down',
               'Up',
               'End',
               'Home',
               'Left',
               'Down',
               'Up',
               'Right',
               'Enter',
               'Backspace',
               'Tab',
               'Space',
               'a',
               'b',
               'c',
               'd',
               'e',
               'f',
               'g',
               'h',
               'i',
               'j',
               'k',
               'l',
               'm',
               'n',
               'o',
               'p',
               'q',
               'r',
               's',
               't',
               'u',
               'v',
               'w',
               'x',
               'y',
               'z',
               'æ',
               'ø',
               'å',
               '0',
               '1',
               '2',
               '3',
               '4',
               '5',
               '6',
               '7',
               '8',
               '9'
              ]
