from .. import config
import os

class Clusters:

    def __init__(self, filename):
        '''
            Performs operations on saved cluster data, as generated by the
            functions in backend/preprocessing/cluster
        '''
        self.path = config.clusters_relpath / filename
        self.data = os.listdir(self.path)
        print(self.data)

if __name__ == '__main__':
    clusters = Clusters('test')
