from .. import config
import os

class Cluster:

    def __init__(self, filename):
        '''
            Performs operations on saved cluster data, as generated by the
            functions in backend/preprocessing/cluster
        '''
        self.path = config.clusters_relpath / filename
        self.data = os.listdir(self.path)
        self.clusters = self.map_clusters()
        print(self.data)

    def map_clusters(self):
        '''
            Creates a dict that can be used to identify clusters and manipulate
            their contents
        '''
        clusters = {}

        return clusters

    def parse_data(self):
        '''
            Generator that parses through each cluster's data
        '''
        pass
